# The frame used for robot commands and pose tracking
robot_base_frame: base_link

# The fixed world frame (usually map if using AMCL)
global_frame: map

# Robot radius (inflated slightly beyond half of footprint diagonal for safe spacing)
robot_radius: 0.35

# Distance between coverage sweep lines (match or slightly overlap robot width)
line_spacing: 0.4

# Angle of sweep lines in degrees (0 = horizontal, 90 = vertical)
coverage_direction: 0.0

# Whether to publish and visualize the full coverage path in RViz
visualize: true

# Optional: topic to publish waypoints to
# If you’re using a script or node to send each goal, this is not needed
# goal_topic: /move_base_simple/goal

# Optional: max planning time (in seconds) or resolution override
# planning_timeout: 10.0
# resolution: 0.05
